### ISSUE TITLE
Creating Admin Role for an existing user

### ISSUE THREAD

**Issue by gaurav-git** [kakwa/ldapcherry#32]
Hi @kakwa 
I am trying to login to ldapcherry as admin but I am not getting any idea about it. I want to create and delete users from admin account. Currently, i am able to login as normal user.

I have already setup openldap server, i have used phpldapadmin to setup some users and groups and organizational unit. The structure is something like below:

![Screenshot from 2019-04-18 13-46-09](https://user-images.githubusercontent.com/5787318/56347737-91e94d80-61e2-11e9-92a1-f713dfe70da5.png)
How should I add or use admin account for ldapcherry?

**Comment by vishwakumba** [comment]
Create the **LDAPCherry Admin role** in `/etc/ldapcherry/roles.yml`

For example: 

```
hello_world_admin_role:
    display_name: Hello_World_Admin_Users
    description: Hello World Admin Users
    LC_admins: True
    backends_groups:
        ad:
            - hello-world
```

* Ensure hello-world group has ben created in your LDAP Server 
* Add the user that you would like to use as an LDAPCherry Admin user to this group

This has been mentioned in the docs.

https://ldapcherry.readthedocs.io/en/latest/deploy.html#defining-ldapcherry-administrator-role

Note : I am using Active Directory. My backend group name is "ad". You may have to use your ldap server variable name defined in `/etc/ldapcherry/ldapcherry.ini`

**Comment by gaurav-git** [comment]
Hi, @vishwakumba  I tried your suggestions and created a new group "AdminGroup" and created a user in it "ldap.admin".

Here is the "roles.yml" file for it:

```
admin-lv3:
    display_name: Administrators Level 3
    description: Super administrators of the system
    LC_admins: True
    backends_groups:
        ldap:
             - cn=admin,cn=AdminGroup,ou=team-xebrium,dc=connect,dc=xebrium,dc=com 
#        ad:
#            - Administrators
#            - Group Policy Creator Owners
#            - Enterprise Admins
#            - Schema Admins
#            - Domain Admins

admin-lv2:
    display_name: Administrators Level 2
    description: Basic administrators of the system
    backends_groups:
        ldap:
            - cn=india-group,ou=team-xebrium,dc=connect,dc=xebrium,dc=com
#        ad:
#            - Administrators

developpers:
    display_name: Developpers
    description: Developpers of the system
    backends_groups:
        ldap:
            - cn=developpers,ou=Group,dc=example,dc=org
            - cn=users,ou=Group,dc=example,dc=org

users:
    display_name: Simple Users
    description: Basic users of the system
    backends_groups:
        ldap:
            - cn=india-group,ou=team-xebrium
```
But it did't work. 
If i set "auth.mode = 'none'" then all users get administrator rights.
